BASE: ['']
TOOLBOX_MODE: "only_test"
SEED: 0
TEST:
  METRICS: ['MAE']
  USE_LAST_EPOCH: True
  DATA:
    FILTERING:
      USE_EXCLUSION_LIST: True
      EXCLUSION_LIST: ['B*', 'AFZ3']
    FS: 30
    DATASET: PhysDrive
    MODALITY: 'MULTI_SPECTRAL'
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW
    DATA_PATH: "/path/to/PhysDrive/RawData/"
    CACHED_PATH: "/path/to/PhysDrive/Processed_test"
    EXP_DATA_NAME: "Diff_160"
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.2
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: MSMamba
  MODEL_DIR: "runs/model_outputs/MSMamba"
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: "pretrained_models/PhysDrive_MSMamba.pth"
